### ISSUE TITLE
Issue running getlightgroup

### ISSUE THREAD

**Issue by sbrp** [lwsrbrts/PoSHue#17] opened 2018-04-03 17:17 UTC
Not sure if this is expected behaviour, but it seems not:

$Group.GetLightGroup("Landing")

Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\Program Files\WindowsPowerShell\Modules\PoSHue\2.0.4\PoSHue.ps1:1081 char:20
+             Return $SelectedGroup
+                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

I can see that there are groups called this as per:

$Group.GetLightGroups()

1  : @{name=Robs Room; lights=System.Object[]; type=Room; state=; recycle=False; class=Bedroom; action=}
2  : @{name=Front Room; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
3  : @{name=Group for wakeup; lights=System.Object[]; type=LightGroup; state=; recycle=True; action=}
4  : @{name=Landing; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
5  : @{name=Spare room 1; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
6  : @{name=Porch; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
7  : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
8  : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
9  : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
10 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
11 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
12 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
13 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
14 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
15 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
16 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
17 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
18 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
19 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
20 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
21 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
22 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
23 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
24 : @{name=Rob's Room; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
25 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
26 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
27 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
28 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
29 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
30 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
31 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
32 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
33 : @{name=Landing; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}

**Comment by lwsrbrts** [comment] 2018-04-03 17:39
It shouldn't no - the issue is that there are multiple groups with the same name, which I see you've mentioned in #16 - GetLightGroup is typically a hidden method and used only to get the reference id as an integer (number) of the one group you're interested in so that you can talk to the bridge about the group. I would not have expected the bridge to allow groups with the same name but then, the primary key is the id...it's just a little confusing to have groups with the same name.

Trying to weasle out of the situation is going to involve some method of allowing the user to provide the  group id directly, or by offering a choice when there are multiple groups with the same name. One for investigation.

Thanks for the issue.

**Comment by sbrp** [comment] 2018-04-03 21:45
The thing is, these groups don't show on the bridge itself. I've not dug through the script in full yet, I thought maybe it was just holding these values in memory, but after a full reboot to make sure, these entries persist (can only see them using getlightgroups).

**Comment by lwsrbrts** [comment] 2018-04-03 21:49
I've just committed some improvements to how groups are handled in this case. The bad news is that it will still be possible to create groups with the same name. The reason for this is that the Hue API permits the multiple names behaviour. That does sound a bit like "You're holding it wrong" but it's the truth (honest guv'nor). The group's ID number is what the bridge uses to identify the group - it doesn't care if every group is called "Landing" - it's the ID that it's interested in.

Instead PoSHue now permits instantiation of the HueGroup object with the group's ID number. If you don't know the number of the group, you can create a blank [HueGroup] object by providing the APIKey (Whitelist Entry) and Bridge IP and then using the GetLightGroups() method.

```powershell
# Create the empty [HueGroup] object using just the whitelist entry and Bridge IP
$Group = [HueGroup]::new($Endpoint, $WhitelistEntry)
# Spit out a list of all groups in the bridge - the numbers are the group IDs
$Group.GetLightGroups()

<#
1  : @{name=Hue Beyond 1; lights=System.Object[]; type=Luminaire; state=; uniqueid=00:37:c7:c8; modelid=HBL001; action=}
2  : @{name=Hue Beyond Down 1; lights=System.Object[]; type=LightSource; state=; uniqueid=00:37:c7:c8-02; action=}
3  : @{name=Hue Beyond Up 1; lights=System.Object[]; type=LightSource; state=; uniqueid=00:37:c7:c8-01; action=}
4  : @{name=Lounge; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
5  : @{name=Hall; lights=System.Object[]; type=Room; state=; recycle=False; class=Hallway; action=}
6  : @{name=Office; lights=System.Object[]; type=Room; state=; recycle=False; class=Office; action=}
7  : @{name=Bedroom; lights=System.Object[]; type=Room; state=; recycle=False; class=Bedroom; action=}
8  : @{name=Group for wakeup; lights=System.Object[]; type=LightGroup; state=; recycle=True; action=}
9  : @{name=Kitchen; lights=System.Object[]; type=Room; state=; recycle=False; class=Living room; action=}
10 : @{name=Test; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
11 : @{name=House; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
12 : @{name=Landing; lights=System.Object[]; type=Room; state=; recycle=False; class=Hallway; action=}
13 : @{name=Group for wakeup; lights=System.Object[]; type=LightGroup; state=; recycle=True; action=}
14 : @{name=HauntedHouseG; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
15 : @{name=HauntedHouseGOdd; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
16 : @{name=HauntedHouseGEven; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
17 : @{name=Office Lamps; lights=System.Object[]; type=LightGroup; state=; recycle=False; action=}
18 : @{name=Dining room; lights=System.Object[]; type=Room; state=; recycle=False; class=Dining; action=}
19 : @{name=Utility; lights=System.Object[]; type=Room; state=; recycle=False; class=Hallway; action=}
#>
```

Now we can instantiate the group object by its ID.

```powershell 
# Make sure to specify an integer (don't "quote" the number)
$Group = [HueGroup]::new(10, $Endpoint, $WhitelistEntry)
# Let's assume we want to delete the group - this method takes no arguments, it deletes the current light group!
$Group.DeleteLightGroup()
```

This will help you delete the existing duplicate named groups.

I still have to create the PowerShell Gallery entry for this version or, if you're manually installing, you can grab the latest code from the repository.

**Comment by sbrp** [comment] 2018-04-03 21:57
Brilliant! I'll give it a whirl.
I've got great hopes for this! I'm getting more into building PowerShell modules recently so I may have a crack at a fork some time.
Have you considered breaking this down into separate files (to separate the functions/classes etc) or nested modules?

**Comment by lwsrbrts** [comment] 2018-04-03 22:06
Just to follow up, the reason the groups don't show in the app is because the _type_ of group you're creating (LightGroup) is no longer considered important. The new "thing" is the `Room` type - which you can create with PoSHue also.

The difference between them is that luminaires (lights) can only be a member of one `Room`, but they can be a member of multiple LightGroups. LightGroups just don't show up in any apps.

The syntax for creating a Room type is:

```powershell
CreateLightGroup(string GroupName, RoomClass RoomClass, string[] LightID)
```

The RoomClass types (types of Room) you can provide are defined in the RoomClass enum which you can enumerate (list) using this code after importing the module:

```powershell
[enum]::GetValues([RoomClass])
```

By example, let's say you want to create a group as a `Room` type called "Closet". A closet is probably an "Other" room type since there's no direct match, so we say that's what this type of Room is.

```powershell
# Create the empty [HueGroup] object using just the whitelist entry and Bridge IP
$Group = [HueGroup]::new($Endpoint, $WhitelistEntry)
# Create the room and put the lights (light IDs 5 and 6) inside. Note that lights 5 and 6 can't be in any other "room".
$Group.CreateLightGroup('Closet', 'Other', @(5,6))
```

Hope that's useful.

**Comment by sbrp** [comment] 2018-04-03 22:11
Thanks!

**Comment by lwsrbrts** [comment] 2018-04-03 22:12
I realise the file that makes up the module is pretty big but if you use folding in something like Visual Studio Code, you can navigate the contents pretty easily. The reason I keep everything in the same file is primarily that's just how it was developed. I'm sure it's possible to decouple the code but it's not something I _need_ to do right now.

**Closed as completed** 2018-04-03 22:17 UTC
